"""First-run local Web credential bootstrap for ``run_web.py``.

Explicit process environment variables always win. When no administrator
password is configured, a private env file outside the repository is created
once and loaded on subsequent starts.
"""

import os
import secrets
from pathlib import Path


ADMIN_USERNAME_ENV = "API_MANAGER_ADMIN_USERNAME"
ADMIN_PASSWORD_ENV = "API_MANAGER_ADMIN_PASSWORD"
SECRET_KEY_ENV = "API_MANAGER_SECRET_KEY"
INSECURE_USERS_ENV = "API_MANAGER_ALLOW_INSECURE_DEFAULT_USERS"
CREDENTIALS_FILE_ENV = "API_MANAGER_WEB_CREDENTIALS_FILE"


def default_credentials_file():
    configured = os.getenv(CREDENTIALS_FILE_ENV)
    if configured:
        return Path(configured).expanduser().resolve()
    workspace_root = Path(__file__).resolve().parent.parent
    return workspace_root / ".secrets" / "api-manager-web.local.env"


def _parse_env_file(path):
    values = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def _load_credentials_file(path):
    values = _parse_env_file(path)
    password = values.get(ADMIN_PASSWORD_ENV)
    secret_key = values.get(SECRET_KEY_ENV)
    if not password or not secret_key:
        raise RuntimeError(
            "local Web credential file is incomplete: {}; expected {} and {}".format(
                path, ADMIN_PASSWORD_ENV, SECRET_KEY_ENV
            )
        )
    username = values.get(ADMIN_USERNAME_ENV) or "admin"
    os.environ.setdefault(ADMIN_USERNAME_ENV, username)
    os.environ.setdefault(ADMIN_PASSWORD_ENV, password)
    os.environ.setdefault(SECRET_KEY_ENV, secret_key)
    return {
        "generated": False,
        "source": "file",
        "path": str(path),
        "username": username,
        "password": None,
    }


def inspect_local_web_credentials(credentials_file=None):
    """Return non-secret status for doctor checks without loading credentials."""
    path = Path(credentials_file).resolve() if credentials_file else default_credentials_file()
    if not path.exists():
        return {"path": str(path), "exists": False, "complete": False}
    try:
        values = _parse_env_file(path)
    except OSError:
        return {"path": str(path), "exists": True, "complete": False}
    return {
        "path": str(path),
        "exists": True,
        "complete": bool(values.get(ADMIN_PASSWORD_ENV) and values.get(SECRET_KEY_ENV)),
    }


def _create_credentials_file(path, username, password, secret_key):
    path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# Generated by api_manger on first local Web startup.\n"
        "# Keep this file private and outside version control.\n"
        "{}={}\n{}={}\n{}={}\n".format(
            ADMIN_USERNAME_ENV,
            username,
            ADMIN_PASSWORD_ENV,
            password,
            SECRET_KEY_ENV,
            secret_key,
        )
    )
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    fd = os.open(str(path), flags, 0o600)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
    except Exception:
        try:
            os.close(fd)
        except OSError:
            pass
        raise
    try:
        os.chmod(str(path), 0o600)
    except OSError:
        # Windows ACLs are not fully represented by POSIX mode bits. The file
        # still lives in the user's private local .secrets directory.
        pass


def bootstrap_local_web_credentials(credentials_file=None):
    """Load or create local administrator credentials before app import."""
    if os.getenv(ADMIN_PASSWORD_ENV):
        return {
            "generated": False,
            "source": "environment",
            "path": "",
            "username": os.getenv(ADMIN_USERNAME_ENV, "admin"),
            "password": None,
        }
    if os.getenv(INSECURE_USERS_ENV, "0") == "1":
        return {
            "generated": False,
            "source": "insecure-default-users",
            "path": "",
            "username": "admin",
            "password": None,
        }

    path = Path(credentials_file).resolve() if credentials_file else default_credentials_file()
    if path.exists():
        return _load_credentials_file(path)

    username = os.getenv(ADMIN_USERNAME_ENV, "admin")
    password = secrets.token_urlsafe(18)
    secret_key = secrets.token_urlsafe(48)
    try:
        _create_credentials_file(path, username, password, secret_key)
    except FileExistsError:
        # Another process completed first-run setup at the same time.
        return _load_credentials_file(path)

    os.environ.setdefault(ADMIN_USERNAME_ENV, username)
    os.environ.setdefault(ADMIN_PASSWORD_ENV, password)
    os.environ.setdefault(SECRET_KEY_ENV, secret_key)
    return {
        "generated": True,
        "source": "generated",
        "path": str(path),
        "username": username,
        "password": password,
    }
